name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

      steps:
        - uses: actions/checkout@v2
        - name: Setup Python # Set Python version
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        # Install pip and pytest
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Test with pytest
          run: python main_lz_c1.py
