name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout actions
    - uses: actions/checkout@v1

    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Update paper list
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python main_lz_c1.py

    - name: commit
      run: |
        git config --global user.email 1031346629@qq.com
        git config --global user.name sym
        git add *
        git commit -m "update" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
